.TH HELLO 1 "February 2025" "Version 1.0" "User Commands"
.SH NAME
hello \- print a friendly greeting
.SH SYNOPSIS
.B hello
[\fB\-h\fR]
[\fB\-\-help\fR]
.SH DESCRIPTION
The
.B hello
command prints a friendly greeting to the standard output.
.PP
This is a simple demonstration program.
.SH OPTIONS
.TP
.BR \-h ", " \-\-help
Display help information and exit.
.SH EXAMPLES
.PP
To run the program:
.PP
.RS
hello
.RE
.SH AUTHOR
Written by the Roff community.
.SH SEE ALSO
.BR groff (1),
.BR troff (1),
.BR nroff (1)
