.TH REFILL 1
.SH NAME
.PP
refill - clean up nroff source files
.SH SYNOPSIS
.B refill
.RB [ --help ]
.RI [ OPTIONS.. ]
.RI [ FILES..]
.SH DESCRIPTION
.PP
Note that major section headings are ALL CAPS.
Subsection headings are usually typed in Title Case.
.PP
Clean up nroff source files by refilling the text.
This does
.i not
refill lines that begin with a period.
.SS "Command Line Options"
.PP
Use these command line options to control refill of
certain nroff documents:
.TP
.B --help
Displays usage and immediately exits
.TP
.BI --output= file
Save the output to
.I file
rather than print to standard output.
.TP
.B -me
Adjust refill to accommodate the
.I -me
macros.
.TP
.B -ms
Adjust refill to accommodate the
.I -ms
macros.
.TP
.B -man
Adjust refill to accommodate the
.I -man
macros.
.SH FILES
.TP
.BI /usr/local/refill/conf/ mac .conf
Configuration files to accommodate nroff macro packages.
The
.BI -m mac
command line options refer to these files by name.
.SH "SEE ALSO"
.BR fmt (1)
