[title]
title = "TOML Example"

[owner]
name = "John Doe"
age = 30

[database]
server = "192.168.1.1"
ports = [8001, 8001, 8002]
connection_max = 5000
enabled = true

[servers]

  # Indentation (spaces or tabs) is allowed but not required
  [servers.alpha]
  ip = "10.0.0.1"
  dc = "eqdc10"

  [servers.beta]
  ip = "10.0.0.2"
  dc = "eqdc10"

[clients]
desktop = "192.168.1.100"

[clients.laptop]
ip = "192.168.1.200"
