Stack(E): trait
  introduces
    empty: -> Stack
    push: Stack, E -> Stack
    pop: Stack -> Stack
    top: Stack -> E
    isEmpty: Stack -> Bool
  asserts
    Stack generated by empty, push
    Stack partitioned by isEmpty
    forall s: Stack, e: E
      pop(push(s, e)) == s;
      top(push(s, e)) == e;
      isEmpty(empty) == true;
      isEmpty(push(s, e)) == false;
