"""Cheap, deterministic reclassifier for the non-COBOL `.cbl`/`.CBL` tail.

Extension-level PLI maps every `.cbl`/`.CBL` file to COBOL. This module reads
a bit of the *content* and reassigns the ones that are not COBOL — the
contamination the study surfaced — at zero API cost. It is bootstrapped from
the LLM-judge labels (see `tools/cobol/eval_reclassify.py` for the experiment
that validates it against the judge as oracle).

Labels
------
- ``cobol``            genuine COBOL program (has divisions / PROGRAM-ID)
- ``cobol-generated`` genuine COBOL, machine-generated (e.g. Micro Focus OO
                      `.designer.cbl` with `class-id` / `$set sourceformat`)
- ``cobol-copybook``  COBOL fragment/include/copybook/unit-test (cobolish but
                      not a full program unit: level+PIC, `EXEC SQL`, TESTSUITE…)
- ``synthetic-placeholder``  `WBC_*_FOO` stubs ("This is cobol file number N")
- ``comic-book-list`` Calibre/CBR reading lists (`<ReadingList>` XML or the
                      binary `CCBridgeLibrary` format) that squat on `.cbl`
- ``binary-data``     non-text bytes with no COBOL signal
- ``other``           text, but no COBOL signal (foreign source, data, docs)

`is_cobol` is True for the three `cobol*` labels. COBOL is checked *before*
the binary bailout, since real COBOL often carries a stray NUL or non-UTF-8
(Shift-JIS/EUC-JP) Japanese comments that would otherwise look binary.
"""

from __future__ import annotations

import re

from . import indicators as ind_mod

_SYNTH_RE = re.compile(r"^\s*this is cobol file number\b", re.I)
_READINGLIST_RE = re.compile(r"<\s*readinglist\b", re.I)
_BOOK_RE = re.compile(r"<\s*book\s+series=", re.I)
_OO_RE = re.compile(r"(?i)\b(class-id|method-id|object-storage section)\b|\$set\s+sourceformat")
_GEN_RE = re.compile(r"(?i)auto-generated|machine-generated|do not (edit|modify)|generated by")
_VERB_RE = re.compile(r"(?i)\b(perform|move|display|accept|compute|initialize|evaluate)\b")
# COBOL fragment/copybook signals (no division headers needed):
_SEQNUM_RE = re.compile(r"(?m)^\d{6}[ *A-Z0-9]")             # fixed-format seq area
_LEVEL_PIC_RE = re.compile(r"(?im)^[\s\d]{0,8}(01|03|05|10|77|88)\s+[\w-]+.*\bpic")
_SQL_INC_RE = re.compile(r"(?i)\b(exec\s+sql|sqlca|sqlda)\b")
_TEST_RE = re.compile(r"(?i)\b(testsuite|testcase|expect)\b")
# A COBOL token required to accept the (weak) seq-number signal, so fixed-width
# numeric *data* files (records starting with digits) aren't taken for copybooks.
_COBOL_TOKEN_RE = re.compile(
    r"(?i)\b(pic|picture|value|comp(-[0-9x])?|occurs|redefines|copy|move|"
    r"perform|display|working-storage|linkage|filler)\b")

COBOL_LABELS = {"cobol", "cobol-generated", "cobol-copybook"}


def _binary_ish(raw: bytes) -> bool:
    """Conservative: heavy NUL density or very low printable ratio.

    A *single* stray NUL is not enough (real COBOL sometimes carries one), and
    high-byte content (Shift-JIS/EUC-JP comments) is allowed as text.
    """
    if not raw:
        return False
    sample = raw[:8192]
    if sample.count(0) > max(2, 0.005 * len(sample)):
        return True
    printable = sum(1 for b in sample if 9 <= b <= 13 or 32 <= b <= 126 or b >= 128)
    return printable / len(sample) < 0.75


def _copybook_signals(head: str) -> bool:
    if (_LEVEL_PIC_RE.search(head) or _SQL_INC_RE.search(head)
            or _TEST_RE.search(head)):
        return True
    # Fixed-format sequence numbers alone are weak — require a COBOL token too,
    # so numeric data files aren't mistaken for copybooks.
    return (len(_SEQNUM_RE.findall(head)) >= 5
            and bool(_COBOL_TOKEN_RE.search(head)))


def classify(filename: str, raw: bytes) -> dict:
    """Return {label, is_cobol, reason}."""
    fn = (filename or "").lower()

    # Binary comic-library format (magic) — catch before anything else.
    if raw[:32].lstrip().startswith(b"CCBridgeLibrary"):
        return _r("comic-book-list", False, "binary CCBridgeLibrary magic")

    # latin-1 never fails and preserves ASCII COBOL keywords even in Shift-JIS
    # / NUL-bearing files, so structural detection still works.
    head = raw[:8000].decode("latin-1", errors="replace")
    low = head.lower()

    # Synthetic WBC placeholder.
    if _SYNTH_RE.match(head):
        return _r("synthetic-placeholder", False, "'This is cobol file number' stub")

    # Comic-book reading list (XML).
    if _READINGLIST_RE.search(low) or ("<?xml" in low and _BOOK_RE.search(low)):
        return _r("comic-book-list", False, "Calibre/CBR <ReadingList> XML")

    # COBOL structure? Check BEFORE the binary bailout.
    text = raw.decode("latin-1", "replace")
    ind = ind_mod.compute(text)
    oo = bool(_OO_RE.search(head))
    is_program = ind.n_divisions >= 1 or bool(ind.program_ids) or oo
    copybook = _copybook_signals(head)
    strong_verbs = len(_VERB_RE.findall(head)) >= 3

    if is_program or (ind.pic_count >= 3 and strong_verbs):
        generated = (fn.endswith(".designer.cbl") or bool(_GEN_RE.search(low))
                     or (oo and "$set sourceformat" in low and ind.n_divisions == 0))
        return _r("cobol-generated" if generated else "cobol", True,
                  f"divisions={ind.n_divisions} pid={bool(ind.program_ids)} oo={oo}")
    if copybook:
        return _r("cobol-copybook", True, "COBOL fragment (level/PIC, SQL, or test)")

    # Not COBOL: binary or other text.
    if _binary_ish(raw):
        return _r("binary-data", False, "non-text bytes, no COBOL signal")
    return _r("other", False, "text, no COBOL structure")


def _r(label: str, is_cobol: bool, reason: str) -> dict:
    return {"label": label, "is_cobol": is_cobol, "reason": reason}


if __name__ == "__main__":
    import argparse
    import json
    from .common import fetch_content
    ap = argparse.ArgumentParser(description="Reclassify one SWHID by content.")
    ap.add_argument("swhid")
    args = ap.parse_args()
    c = fetch_content(args.swhid)
    print(json.dumps({"filename": c.filename, **classify(c.filename, c.raw)}, indent=2))
