.TH HELLO 1 "February 2026" "Version 1.0" "User Commands"
.SH NAME
hello \- print a greeting message
.SH SYNOPSIS
.B hello
[\fB\-n\fR \fIname\fR]
.SH DESCRIPTION
The
.B hello
command prints a greeting message to standard output.
.SH OPTIONS
.TP
.BR \-n " " \fIname\fR
Specify the name to greet. Default is "World".
.SH EXAMPLES
.nf
hello
hello -n Alice
.fi
.SH AUTHOR
Written by the GROFF community.
.SH SEE ALSO
.BR groff (1),
.BR man (1)
