@startuml
!include style.puml
hide empty members

class IEntity
class Leaf
class EntityList

IEntity <|-- Leaf
IEntity <|-- EntityList

class Group
class Code
class Link
class Note
class Namespace

Group <|-- Code
Group <|-- Link
Group <|-- Note
Group <|-- Namespace

class Display
class StringBounder
class UmlDiagram
class UmlDiagramType
class AbstractPSystem
class PSystemError

UmlDiagram <|-- AbstractPSystem
AbstractPSystem <|-- PSystemError

class UmlSource
class SkinParam
class Pragma

@enduml