openrouter:
  api_key_env: OPENROUTER_API_KEY
  base_url: https://openrouter.ai/api/v1/chat/completions

models_pool:
  #- openai/gpt-4o
  # - openai/gpt-5
  #- mistralai/codestral-2508
  #- bigcode/starcoder2-15b-instruct
  #- deepseek/deepseek-chat-v3-0324
  - x-ai/grok-4-fast
  - google/gemini-2.5-pro
  #- qwen/qwen3-vl-32b-instruct
  #- minimax/minimax-m2:free
  #- anthropic/claude-3.5-sonnet
  #- anthropic/claude-4.5-sonnet
  #- meta-llama/llama-3.1-70b-instruct
  #- google/gemini-2.5-flash

limits:
  max_code_lines: 200
  max_name_len: 120
