openrouter:
  api_key_env: OPENROUTER_API_KEY
  base_url: https://openrouter.ai/api/v1/chat/completions

models_pool:
  - openai/gpt-4o
  - anthropic/claude-3.5-sonnet
  - anthropic/claude-4.5-sonnet
  - meta-llama/llama-3.1-70b-instruct
  - google/gemini-flash-1.5

limits:
  max_code_lines: 200
  max_name_len: 120
