[ uuid(12345678-4321-1234-4321-123456789abc),
  version(1.0),
  pointer_default(unique)
]
interface ICalculator
{
    long Add([in] long a, [in] long b);
    long Subtract([in] long a, [in] long b);
    long Multiply([in] long a, [in] long b);
    long Divide([in] long a, [in] long b,
                [out] long *remainder);
    void Shutdown(void);
}