media nclMediaPlayer {
	area = "main";
	region = "main";
	descriptor = "nclDescriptor";
	property name="mediaTime" value="0";
	property name="mediaDuration" value="0";
	property name="mediaState" value="playing";
	property name="mediaType" value="video";
	property name="mediaSource" value="";
	property name="mediaSink" value="";
	property name="mediaLoop" value="false";
	property name="mediaAutoplay" value="true";
	property name="mediaControls" value="true";
	property name="mediaFullScreen" value="false";
}
